config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "flats#index"

  resources :flats do
    collection do
      get :research
    end
    resources :bookings, only: [:new, :create] do
      member do
        get :approve
        get :reject
      end
    end
    get '/confirmation', to: 'bookings#confirmation', as: 'confirmation'
    get '/dashboard', to: 'bookings#dashboard', as: 'dashboard'
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  validates :departure_date, presence: true
  validates :arrival_date, presence: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :flat_equipments
  has_many :flats, through: :flat_equipments
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  validates :number_of_guests, presence: true
  validates :price, presence: true
  validates :name, presence: true, uniqueness: true
  validates :planet, presence: true
  # has_many :reviews, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings
  has_many :flat_equipments
  has_many :equipments, through: :flat_equipments
  accepts_nested_attributes_for :equipments
  has_many_attached :images
end

app/models/flat_equipment.rb
class FlatEquipment < ApplicationRecord
  belongs_to :flat
  belongs_to :equipment
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :telepathic_code, presence: true, uniqueness: true
  validates :specie, presence: true
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:approve, :reject]

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.flat = @flat
    @booking.save
    redirect_to flat_confirmation_path
  end

  def confirmation
  end

  def dashboard
    @bookings_as_tenant = current_user.bookings.includes(:flat)
    @bookings_as_owner = Booking.includes(:flat).where(flats: { owner: current_user })
  end


  def approve
    if @booking.flat.owner == current_user
      @booking.update(status: 'approved')
    else
      flash[:alert] = "You don't have permission to do that"
    end
    redirect_to flat_dashboard_path
  end

  def reject
    if @booking.flat.owner == current_user
      @booking.update(status: 'rejected')
    else
      flash[:alert] = "You don't have permission to do that"
    end
    redirect_to flat_dashboard_path
  end



  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = @flat.bookings.new
    @review = Review.new
    @reviews = @flat.reviews
  end

  def research
    @flats = Flat.where('planet ILIKE ?', params[:planet]).where('number_of_guests >= ?', params[:number_of_guests])
  end

  def new
    @flat = Flat.new
    @equipment = Equipment.all
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.owner_id = current_user.id
    if @flat.save
      redirect_to flats_path(@flat)
    else
      @equipment = Equipment.all
      render :new
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :planet, :description, :price, :number_of_guests, equipment_ids: [], images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_flat, only: %i[new create]

  def index
    @reviews = Review.all
  end

  def average_rating
    @review = reviews.average(:rating).round(1)
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.flat = @flat
    if @review.save
      redirect_to flat_path(@flat)
    else
      render partial: 'new', status: :unprocessable_entity
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/confirmation.html.erb
<div class="container col-6">
    <%= image_tag("confimation.jpg", size: "75x75") %>
    <div class="section-infos">
      <h1>Booking Confirmed!</h1>
      <p>Your booking has been successfully created.</p>
    </div>
  <button type="button" class="btn-ghost">
    <%= link_to "Go to my account", flat_dashboard_path %>
  </button>
</div>

app/views/bookings/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="show-header">
        <h2>Your bookings as a tenant</h2>
        <div class="d-flex flex-row">
          <% @bookings_as_tenant.each do |booking| %>
            <div class="card" style="width: 18rem;">
              <% if booking.flat.images.attached? %>
                <%= image_tag url_for(booking.flat.images.first), class: 'card-img-top', alt: 'Flat Image' %>
              <% else %>
                <p>No image available</p>
              <% end %>
              <div class="card-body">
                <h4 class="card-title"><%= booking.flat.name %></h4>
                <p class="card-text"><%= booking.flat.planet %></p>
                <h3>Booking Details</h3>
                <p>Arrival Date: <%= booking.arrival_date %></p>
                <p>Departure Date: <%= booking.departure_date %></p>
                <p>Status: <%= booking.status.capitalize %></p>
                <% if booking.status == 'pending' %>
                  <%= link_to 'Approve', approve_flat_booking_path(booking.flat, booking), method: :put, class: "search_btn" %>
                  <%= link_to 'Reject', reject_flat_booking_path(booking.flat, booking), method: :put,  class: "search_btn" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <h2>Bookings for your flats</h2>
        <div class="d-flex flex-row">
          <% @bookings_as_owner.each do |booking| %>
            <div class="card" style="width: 18rem;">
              <% if booking.flat.images.attached? %>
                <%= image_tag url_for(booking.flat.images.first), class: 'card-img-top', alt: 'Flat Image' %>
              <% else %>
                <p>No image available</p>
              <% end %>
              <div class="card-body">
                <h4 class="card-title"><%= booking.flat.name %></h4>
                <p class="card-text"><%= booking.flat.planet %></p>
                <h3>Booking Details</h3>
                <p>Arrival Date: <%= booking.arrival_date %></p>
                <p>Departure Date: <%= booking.departure_date %></p>
                <p>Status: <%= booking.status.capitalize %></p>
                <% if booking.status == 'pending' %>
                  <%= link_to 'Approve', approve_flat_booking_path(booking.flat, booking), method: :put, class: "search_btn" %>
                  <%= link_to 'Reject', reject_flat_booking_path(booking.flat, booking), method: :put,  class: "search_btn" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="search_container">
        <%= form_tag research_flats_path, method: :get, class: 'form-inline' do %>
          <div id="search_field">
            <div>Planet</div>
            <%= text_field_tag :planet, params[:planet], placeholder: "Search for a planet" %>
          </div>
          <div id="search_field">
            <div>Number of travelers</div>
            <%= text_field_tag :number_of_guests, params[:number_of_guests], placeholder: "Number of guests" %>
          </div>
          <div>
            <%= submit_tag "GO", class: 'search_btn' %>
          </div>
        <% end %>
      </div>

      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
          <% @flats.each do |flat| %>
            <div class="col">
              <%= link_to flat_path(flat.id), :action => 'go', class: 'card-link' do %>
                <div class="card" >
                  <% if flat.images.attached? %>
                    <%= image_tag url_for(flat.images.first), class: 'card-img-top', alt: 'Flat Image' %>
                  <% else %>
                    <p>No image available</p>
                  <% end %>
                  <div class="card-body">
                    <h4 class="card-title text-truncate"><%= flat.name %></h4>
                    <p class="card-text"><%= flat.planet %></p>
                    <div class="card-bottom">
                      <i class="fa-brands fa-rebel" style="color: #71a4ac;"></i><%= flat.price %> / night
                      <br>
                      <i class="fa-solid fa-user-group" style="color: #71a4ac;"></i><%= flat.number_of_guests %> travelers
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container col-6">
 <div class="section-infos">
  <h1>List your property on Farbnb</h1>
 </div>
<div class="card-booking">
  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name, placeholder: 'Enter the name of your flat' %>
    <%= f.input :planet, placeholder: 'Enter the planet where your flat is located' %>
    <%= f.input :description, placeholder: 'Enter a description' %>
    <%= f.label :price %><i class="fa-brands fa-rebel" style="color: #71a4ac; margin-left: 5px;"></i>
    <%= f.input :price , placeholder: 'Enter the price per nigth', label: false %>
    <%= f.input :number_of_guests, placeholder: 'Enter the number of guests your flight can welcome' %>
</div>

<div class="card-booking">
    <h5>Select Equipment:</h5>
    <% @equipment.each do |equipment| %>
      <div>
        <%= check_box_tag 'flat[equipment_ids][]', equipment.id, @flat.equipments.include?(equipment) %>
        <%= label_tag "flat_equipment_ids_#{equipment.id}", equipment.name %>
      </div>
    <% end %>
</div>

<div class="card-booking">
    <h5>Upload Images:</h5>
    <%= f.input :images, as: :file, input_html: { multiple: true} %>
    <%= f.submit "Register your flat and start earning Solaris !", class: "search_btn mt-2 text-center" %>
  <% end %>
</div>
</div>

app/views/flats/research.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <% if @flats.empty? %>
          <p>No flats available. <%= button_to 'Go back to homepage', root_path, method: :get, class: 'btn-ghost' %></p>
        <% else %>
          <div class="flats-header">
            <h1>Those flats may interest you</h1>
          </div>

          <div class="d-flex">
            <% @flats.each do |flat| %>
              <%= link_to flat_path(flat.id) do %>
                <div class="card" style="width: 18rem;">
                  <% if flat.images.attached? %>
                    <%= image_tag url_for(flat.images.first), class: 'card-img-top', alt: 'Flat Image' %>
                  <% else %>
                    <p>No image available</p>
                  <% end %>
                  <div class="card-body">
                    <h4 class="card-title"><%= flat.name %></h4>
                    <p class="card-text"><%= flat.planet %></p>
                    <div class="card-bottom">
                      <i class="fa-brands fa-rebel" style="color: #71a4ac;"></i><%= flat.price %> per night
                      <br>
                      <i class="fa-solid fa-user-group" style="color: #71a4ac;"></i><%= flat.number_of_guests %> travelers
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="show-header">
        <div>
          <h1 class="card-title"><%= @flat.name %></h1>
        </div>
        <div class="undertitle-info">
          <div class="undertitle-info-item">
            Planete : <%= @flat.planet %>
          </div>
          <div class="undertitle-info-item">
            For <%= @flat.number_of_guests %> travelers
          </div class="undertitle-info-item">
          <div>
            Price : <%= @flat.price %> <i class="fa-brands fa-rebel" style="color: #71a4ac;"></i>
          </div>
        </div>
      </div>
    </div>




    <div class="show-img" style="<%= @flat.images.attached? ? "background-image: url(#{url_for(@flat.images.first)})" : "" %>">
    </div>

    <div class="d-flex">
      <div class="show-card-body col-8">
        <p class="card-text"><%= @flat.description %></p>
        <div class="section-infos">
          <h4>Equipment</h4>
        </div>
        <ul>
          <% @flat.equipments.each do |equipment| %>
            <li><%= equipment.name %></li>
          <% end %>
        </ul>
        <div class="section-infos">
          <h4>Reviews</h4>
        </div>
          <%= render partial: 'reviews/new', locals: { flat: @flat } %>
      </div>
  <div class="show-card-booking col-4" data-controller='datepickr'>
    <div class="card-booking">
      <h6><b><%= @flat.price %> <i class="fa-brands fa-rebel" style="color: #71a4ac;"></i>(solaris) </b> / night</h6>
      <%= form_with(model: [@flat, @booking]) do |form| %>
        <div class="input-group">
          <span class="input-group-text" id="start-date-label">From:</span>
          <%= form.text_field :arrival_date, class: "form-control", placeholder: "12/10/2017", aria: { label: "start-date", describedby: "start-date-label" }, data: {datepickr_target: 'startDate'} %>
        </div>
        <div class="input-group mt-2">
          <span class="input-group-text" id="end-date-label">To:</span>
          <%= form.text_field :departure_date, class: "form-control", placeholder: "18/10/2017", aria: { label: "end-date", describedby: "end-date-label" }, data: {datepickr_target: 'endDate'} %>
        </div>
        <%= form.submit "Book this experience", class: "search_btn mt-2 text-center", style: "width: 100%" %>
      <% end %>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FARBNB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "farbnb_logo.png", alt: "Farbnb" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/flats", class: "btn-ghost" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add your flat", new_flat_path(@flat), class: "btn-ghost" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "alien1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Connexion", " /users/sign_in", class: "dropdown-item" %>
              <%= link_to "Account", "  /flats/:flat_id/dashboard", class: "dropdown-item" %>
              <%= link_to "Log out", "/users/sign_out", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "btn-ghost" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_new.html.erb
<div class="reviews">
  <li class="list-group-item">Average Rating:
    <% if @flat.reviews.any? %>
      <%= @flat.reviews.average(:rating)&.round(1) %>/5
    <% else %>
      No reviews yet
    <% end %>
  </li>

  <ul class="list-group">
    <% if @flat.reviews.any? %>
      <% @flat.reviews.each do |review| %>
        <li class="list-group-item"><%= review.content %> - <%= review.rating %>/5</li>
      <% end %>
    <% else %>
      <li class="list-group-item">No reviews yet</li>
    <% end %>
  </ul>
</div>

<div class="card-review">
<div class="card-booking">
  <h1>Add a new review</h1>
  <%= simple_form_for [@flat, @review] do |f| %>
    <div class="form-group">
      <%= f.label :content, "Review" %>
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :rating, "Rating" %>
      <%= f.select :rating, options_for_select((1..5).map { |num| ["#{num}/5", num] }), { label: "Select a rating" }, class: "form-control" %>
    </div>
    <%= f.submit "Submit review", class: "search_btn mt-2 text-center" %>
  <% end %>
</div>
</div>